name: jaguar_resty
description: Build fluent functional REST clients. Supports interceptors, cookies, multipart forms and authenticators.
version: 2.8.4
homepage: https://github.com/Jaguar-dart/client
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  http: ^0.11.3
  async: ^2.0.6
  http_parser: ^3.1.1
  client_cookie: ^2.1.5
  collection: ^1.14.6
  auth_header: ^2.1.2
  path: ^1.6.2
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.0
  jaguar: ^2.2.20
